### ISSUE TITLE
Could you push some examples ? 

### ISSUE THREAD

**Issue by MoMe36** [navneet-nmk/pytorch-rl#1]
Hey, nice work here ! 

Could you maybe add some more examples?  

Thanks !

**Comment by navneet-nmk** [comment]
Hi! Thanks for the response. 
I am currently working on a paper for ICML and not getting much time. I will definitely add more examples later. 

Thanks!

**Comment by andjsmile** [comment]
You have done a good job! ? But you don't provide a documentation or no examples, so it's not well known. I hope that you can provide the documentation as soon as possible, thanks for sharing.

**Comment by DKurome** [comment]
`Traceback (most recent call last):
  File "/home/dk/pytorch-rl-master/train_ddpg.py", line 70, in <module>
    trainer.train()
  File "/home/dk/pytorch-rl-master/Training/trainer.py", line 124, in train
    state = to_tensor(state, use_cuda=self.cuda)
  File "/home/dk/pytorch-rl-master/Utils/utils.py", line 91, in to_tensor
    v = torch.cuda.FloatTensor(v)
TypeError: new(): data must be a sequence (got dict)`

I don't know how to solve the problem, could you give me some advice,such as the pytorch version?
